// v0.3.2 vocabulary and enum layer. Kept separate from the legacy compact
// dictionary so incremental translations can be reviewed without duplicating
// pages or database enum values.
export const zhCNOverrides: Record<string, string> = {
  profileTemplates: 'Agent 行为模板', agentTemplates: 'Agent 行为模板', profiles: 'Agent 配置文件', runtimes: '用户运行环境', runtimeTemplates: '运行环境模板', providers: '模型供应商', secrets: '凭据管理',
  runtimeManagement: '运行环境管理', runtimeProvisioning: '运行环境配置', provision: '配置运行环境', runtimeErrors: '运行环境异常', runtimeFilter: '运行环境', runtime: '运行环境',
  runtimeInfrastructure: '运行环境基础设施', runtimeHosts: '运行主机', runtimeHost: '运行主机', addRuntimeHost: '添加运行主机', editRuntimeHost: '编辑运行主机', hostName: '主机名称', hostIp: '主机 / IP', authentication: '身份鉴权', sshPassword: 'SSH 密码', dockerSocketPath: 'Docker Socket 路径', dockerBinary: 'Docker 二进制程序', runtimeDefaults: '运行环境默认值', scheduling: '调度', placementMode: '调度模式', placementRule: '调度规则', mockSchedulingRule: '根据主机状态、可用 CPU、内存和标签进行模拟调度',
  defaultRuntimeProvider: '默认运行环境提供方', defaultHermesImage: '默认 Hermes 镜像', defaultDockerSocket: '默认 Docker Socket 路径', provisionTimeout: '配置超时', healthCheckInterval: '健康检查间隔', hostIpAddress: '主机 / IP', lastCheck: '最后检查', containers: '容器', total: '总量', allocated: '已分配', actualUsage: '实际使用', labels: '标签',
  credential: '凭据', apiKey: 'API Key', apiToken: 'API Token', credentialConfiguredHint: '凭据已配置。留空将保持当前值。', credentialRequiredHint: '此值仅会以安全引用形式保存，且不会再次显示。', leaveBlankUnchanged: '留空保持不变', connectionTested: '连接测试已完成', inventoryUpdated: '主机清单已更新', drain: '排空主机', moreActions: '更多操作',
  enum_online: '在线', enum_offline: '离线', enum_degraded: '异常', enum_maintenance: '维护中', enum_draining: '排空中', enum_unknown: '未知', enum_enabled: '已启用', enum_disabled: '已禁用', enum_running: '运行中', enum_stopped: '已停止', enum_configured: '已配置', enum_not_configured: '未配置', enum_pending: '待处理', enum_approved: '已批准', enum_rejected: '已拒绝', enum_active: '已启用', enum_suspended: '已暂停', enum_archived: '已归档', enum_error: '错误', enum_failed: '失败', enum_completed: '已完成', enum_published: '已发布', enum_indexed: '已索引',
  agentTemplateBoundary: '可复用的 Agent 行为模板；基础设施属于运行环境模板。', profileBoundary: '当前用户 Agent 配置文件的最终模型、Skills 和知识库。', executionBoundary: '执行遥测与控制平面审计分离。', mockProvider: '模拟运行环境提供方', mockProviderBoundary: '模拟 Provider 边界；不会调用生产服务。',
  associatedRoles: '关联角色', associatedProfiles: '关联配置文件', providerModels: '供应商模型', authType: '鉴权类型', secret: '凭据', secretReference: '凭据引用', runtimeCount: '用户运行环境数量', capacity: '资源容量', runtimeEndpoint: '运行环境端点', userRuntimes: '用户运行环境',
}

export const enUSOverrides: Record<string, string> = {
  runtimeInfrastructure: 'Runtime Infrastructure', runtimeHost: 'Runtime Host', addRuntimeHost: 'Add Runtime Host', editRuntimeHost: 'Edit Runtime Host', hostName: 'Host Name', hostIp: 'Host / IP', authentication: 'Authentication', sshPassword: 'SSH Password', dockerSocketPath: 'Docker Socket Path', dockerBinary: 'Docker Binary', runtimeDefaults: 'Runtime Defaults', scheduling: 'Scheduling', placementMode: 'Placement Mode', placementRule: 'Placement Rule', mockSchedulingRule: 'Mock scheduling by host status, available CPU, memory and labels',
  defaultRuntimeProvider: 'Default Runtime Provider', defaultHermesImage: 'Default Hermes Image', defaultDockerSocket: 'Default Docker Socket Path', provisionTimeout: 'Provision Timeout', healthCheckInterval: 'Health Check Interval', lastCheck: 'Last Check', containers: 'Containers', total: 'Total', allocated: 'Allocated', actualUsage: 'Actual Usage', labels: 'Labels', credential: 'Credential', apiKey: 'API Key', apiToken: 'API Token', credentialConfiguredHint: 'Credential configured. Leave blank to retain it.', credentialRequiredHint: 'This value is saved as a secure reference and is not displayed again.', leaveBlankUnchanged: 'Leave blank to keep unchanged', connectionTested: 'Connection tested', inventoryUpdated: 'Host inventory updated', drain: 'Drain', moreActions: 'More actions',
  'enum.online': 'Online', 'enum.offline': 'Offline', 'enum.degraded': 'Degraded', 'enum.maintenance': 'Maintenance', 'enum.draining': 'Draining', 'enum.unknown': 'Unknown', 'enum.enabled': 'Enabled', 'enum.disabled': 'Disabled', 'enum.running': 'Running', 'enum.stopped': 'Stopped', 'enum.configured': 'Configured', 'enum.not_configured': 'Not Configured', 'enum.pending': 'Pending', 'enum.approved': 'Approved', 'enum.rejected': 'Rejected',
}
