// Completion hotfix vocabulary for UI that was added incrementally during the
// v0.2/v0.3 demo work. Keeping these keys in one reviewable layer prevents
// database values and one-off English literals from leaking into zh-CN UI.
export const enUSCompletion: Record<string, string> = {
  searchAndSelect: 'Search and select', allRelatedEntities: 'All related entities',
  organizationUsers: 'Organization & Users', importUsers: 'Import users', downloadTemplate: 'Download template', exportCurrentFilter: 'Export current filter',
  searchDepartment: 'Search departments', addDepartment: 'Add department', searchUsers: 'Search users', runtimeStatus: 'Runtime status', agentTemplateProfile: 'Agent Template / Profile',
  enable: 'Enable', moveAssignRole: 'Move / assign role', export: 'Export', allUsers: 'All users', overview: 'Overview', remove: 'Remove',
  effectiveAgentTemplates: 'Effective Agent Templates', code: 'Code', manager: 'Manager', departmentDependencies: 'Department dependencies',
  departmentDeleteBlocked: 'This department cannot be deleted while dependencies exist.', childDepartments: 'Child departments', agentTemplateBindings: 'Agent Template bindings', knowledgeBindings: 'Knowledge bindings', runtimePolicies: 'Runtime policies',
  batchUserAction: 'Batch user action', moveDepartment: 'Move department', assignRoleAction: 'Assign role', upload: 'Upload', validationPreview: 'Validation preview', confirm: 'Confirm',
  validRows: 'Valid rows', invalidRows: 'Invalid rows', selected: 'selected', row: 'Row', error: 'Error', back: 'Back', continue: 'Continue', confirmImport: 'Confirm import', createUsersConfirmPrefix: 'Create ', createUsersConfirmSuffix: ' users?', tenMinutes: '10 min', sixtySeconds: '60 sec',
  discardUnsavedChanges: 'Discard unsaved changes?', dangerousActionConfirm: 'This action can affect existing data. Do you want to continue?', associatedUsers: 'Associated users', addUsers: 'Add users', roleBindingSummary: 'All user associations use RoleBinding.',
  systemRole: 'System role', customRole: 'Custom role', addUsersToRole: 'Add users to role', infrastructurePolicyTemplates: 'Infrastructure policy templates',
  runtimeTemplateBoundary: 'CPU, memory, storage and runtime policy only. Agent model, Skills and Knowledge belong to Agent Templates.', associatedRoles: 'Associated roles', policyRoles: 'Policy roles', rolePriority: 'Role priority', departmentPriority: 'Department priority', defaultDepartments: 'Default departments',
  unsavedChanges: 'Unsaved changes', reset: 'Reset', saveChanges: 'Save changes', updatedAtPrefix: 'Updated', credentialRequiresReentry: 'Re-enter credential', credentialReentryHint: 'The previous credential used a non-recoverable legacy format. Enter it again to enable integrations.',
  sourceRoles: 'Source roles', personalLabel: 'Personal', profileInstances: 'Profile instances', profileControls: 'Profile controls', emergencyDemoStop: 'Emergency demo stop',
  setting_organization_name: 'Organization name', setting_default_language: 'Default language', setting_timezone: 'Timezone', setting_local_account_enabled: 'Local account enabled', setting_sso_reserved_status: 'SSO reserved status', setting_session_ttl: 'Session TTL (minutes)', setting_password_minimum_length: 'Password minimum length', setting_login_failure_lockout: 'Login failure lockout', setting_audit_retention_days: 'Audit retention days', setting_high_risk_threshold: 'High-risk threshold', setting_runtime_provisioning: 'Provisioning mode', setting_default_runtime_template: 'Default Runtime Template', setting_default_runtime_provider: 'Default Runtime Provider', setting_default_hermes_image_version: 'Default Hermes image version', setting_model_access_mode: 'Model access mode', setting_default_model: 'Default model', setting_skill_submission_enabled: 'Skill submission enabled', setting_review_required: 'Review required', setting_default_risk_policy: 'Default risk policy', setting_default_document_status: 'Default document status', setting_knowledge_approval_required: 'Knowledge approval required', setting_default_export_format: 'Default export format', setting_critical_risk_notifications: 'Critical-risk notifications', setting_approval_notifications: 'Approval notifications', setting_runtime_failure_notifications: 'Runtime-failure notifications',
  enum_requires_reentry: 'Re-enter credential', enum_missing: 'Missing', enum_global: 'Global', enum_organization: 'Organization', enum_department: 'Department', enum_role: 'Role', enum_user: 'User', enum_profile: 'Profile', enum_mandatory: 'Mandatory', enum_optional: 'Optional', enum_default: 'Default', enum_low: 'Low', enum_medium: 'Medium', enum_high: 'High', enum_critical: 'Critical', enum_waiting_approval: 'Waiting for approval', enum_cancelled: 'Cancelled', enum_draft: 'Draft', enum_private: 'Private', enum_background: 'Background', enum_qa: 'Q&A', enum_markdown: 'Markdown', enum_procedure: 'Procedure / SOP', enum_allow: 'Allow', enum_deny: 'Deny', enum_success: 'Success', enum_denied: 'Denied', enum_failure: 'Failure', enum_openai: 'OpenAI', enum_openrouter: 'OpenRouter', enum_google: 'Google', enum_nous: 'Nous', enum_custom: 'Custom', enum_enterprise_gateway: 'Enterprise Gateway', enum_hermes_native: 'Hermes Native', enum_custom_gateway: 'Custom Gateway', enum_api_key: 'API Key', enum_token: 'API Token',
}

export const zhCNCompletion: Record<string, string> = {
  searchAndSelect: '搜索并选择', allRelatedEntities: '全部关联资源',
  organizationUsers: '组织与用户', importUsers: '导入用户', downloadTemplate: '下载模板', exportCurrentFilter: '导出当前筛选结果',
  searchDepartment: '搜索部门', addDepartment: '添加部门', searchUsers: '搜索用户', runtimeStatus: '运行环境状态', agentTemplateProfile: 'Agent 行为模板 / 配置文件',
  enable: '启用', moveAssignRole: '移动 / 分配角色', export: '导出', allUsers: '全部用户', overview: '概览', remove: '移除',
  effectiveAgentTemplates: '生效的 Agent 行为模板', code: '编码', manager: '负责人', departmentDependencies: '部门依赖关系',
  departmentDeleteBlocked: '该部门仍存在依赖关系，无法删除。', childDepartments: '子部门', agentTemplateBindings: 'Agent 行为模板绑定', knowledgeBindings: '知识库绑定', runtimePolicies: '运行环境策略',
  batchUserAction: '批量用户操作', moveDepartment: '移动部门', assignRoleAction: '分配角色', upload: '上传', validationPreview: '验证预览', confirm: '确认',
  validRows: '有效行', invalidRows: '无效行', selected: '已选择', row: '行', error: '错误', back: '返回', continue: '继续', confirmImport: '确认导入', createUsersConfirmPrefix: '创建 ', createUsersConfirmSuffix: ' 个用户？', tenMinutes: '10 分钟', sixtySeconds: '60 秒',
  discardUnsavedChanges: '放弃未保存的修改？', dangerousActionConfirm: '此操作可能影响现有数据。是否继续？', associatedUsers: '关联用户', addUsers: '添加用户', roleBindingSummary: '所有用户关联均使用 RoleBinding。',
  systemRole: '系统角色', customRole: '自定义角色', addUsersToRole: '向角色添加用户', infrastructurePolicyTemplates: '基础设施策略模板',
  runtimeTemplateBoundary: '仅包含 CPU、内存、存储和运行环境策略。Agent 模型、Skills 和知识库属于 Agent 行为模板。', associatedRoles: '关联角色', policyRoles: '策略角色', rolePriority: '角色优先级', departmentPriority: '部门优先级', defaultDepartments: '默认部门',
  unsavedChanges: '存在未保存的修改', reset: '重置', saveChanges: '保存修改', updatedAtPrefix: '更新时间', credentialRequiresReentry: '需要重新输入凭据', credentialReentryHint: '原凭据使用不可恢复的旧格式。请重新输入后再启用集成。',
  sourceRoles: '来源角色', personalLabel: '个人', profileInstances: '配置文件实例', profileControls: '配置文件控制', emergencyDemoStop: '紧急演示停止',
  setting_organization_name: '组织名称', setting_default_language: '默认语言', setting_timezone: '时区', setting_local_account_enabled: '启用本地账号', setting_sso_reserved_status: 'SSO 预留状态', setting_session_ttl: '会话有效期（分钟）', setting_password_minimum_length: '最小密码长度', setting_login_failure_lockout: '登录失败锁定', setting_audit_retention_days: '审计保留天数', setting_high_risk_threshold: '高风险阈值', setting_runtime_provisioning: '配置方式', setting_default_runtime_template: '默认运行环境模板', setting_default_runtime_provider: '默认运行环境提供方', setting_default_hermes_image_version: '默认 Hermes 镜像版本', setting_model_access_mode: '模型访问模式', setting_default_model: '默认模型', setting_skill_submission_enabled: '允许提交 Skill', setting_review_required: '需要审核', setting_default_risk_policy: '默认风险策略', setting_default_document_status: '默认文档状态', setting_knowledge_approval_required: '知识库需要审批', setting_default_export_format: '默认导出格式', setting_critical_risk_notifications: '严重风险通知', setting_approval_notifications: '审批通知', setting_runtime_failure_notifications: '运行环境失败通知',
  enum_requires_reentry: '需要重新输入', enum_missing: '未配置', enum_global: '全局', enum_organization: '组织', enum_department: '部门', enum_role: '角色', enum_user: '用户', enum_profile: '配置文件', enum_mandatory: '强制', enum_optional: '可选', enum_default: '默认', enum_low: '低', enum_medium: '中', enum_high: '高', enum_critical: '严重', enum_waiting_approval: '等待审批', enum_cancelled: '已取消', enum_draft: '草稿', enum_private: '私有', enum_background: '背景资料', enum_qa: '问答', enum_markdown: 'Markdown', enum_procedure: '流程 / SOP', enum_allow: '允许', enum_deny: '拒绝', enum_success: '成功', enum_denied: '已拒绝', enum_failure: '失败', enum_openai: 'OpenAI', enum_openrouter: 'OpenRouter', enum_google: 'Google', enum_nous: 'Nous', enum_custom: '自定义', enum_enterprise_gateway: '企业网关', enum_hermes_native: 'Hermes Native', enum_custom_gateway: '自定义网关', enum_api_key: 'API Key', enum_token: 'API Token',
}
