export const routes = {
  login: '/login',
  workspace: {
    root: '/workspace',
    chat: '/workspace/chat',
    agents: '/workspace/agents',
    models: '/workspace/models',
    skills: '/workspace/skills',
    knowledge: '/workspace/knowledge',
    channels: '/workspace/channels',
    usage: '/workspace/usage',
    settings: '/workspace/settings',
  },
  admin: {
    root: '/admin',
    overview: '/admin/overview',
    organization: '/admin/organization',
    roles: '/admin/roles',
    agentProfiles: '/admin/agent-profiles',
    agentTemplates: '/admin/agent-templates',
    models: '/admin/models',
    modelProviders: '/admin/model-providers',
    skills: '/admin/skills',
    knowledge: '/admin/knowledge',
    runtime: '/admin/runtime',
    runtimeHosts: '/admin/runtime-hosts',
    runtimeTemplates: '/admin/runtime-templates',
    scheduling: '/admin/scheduling',
    executions: '/admin/executions',
    approvals: '/admin/approvals',
    audit: '/admin/audit',
    usage: '/admin/usage',
    quotas: '/admin/quotas',
    settings: '/admin/settings',
    secrets: '/admin/secrets',
    profile: '/admin/profile',
  },
} as const

export const legacyAdminRoutes: Record<string, string> = {
  '/organization': routes.admin.organization,
  '/users': routes.admin.organization,
  '/departments': routes.admin.organization,
  '/roles': routes.admin.roles,
  '/profiles': routes.admin.agentProfiles,
  '/agent-templates': routes.admin.agentTemplates,
  '/models': routes.admin.models,
  '/model-providers': routes.admin.modelProviders,
  '/skills': routes.admin.skills,
  '/skill-reviews': routes.admin.skills,
  '/knowledge-bases': routes.admin.knowledge,
  '/runtimes': routes.admin.runtime,
  '/runtime-hosts': routes.admin.runtimeHosts,
  '/scheduling': routes.admin.scheduling,
  '/runtime-templates': routes.admin.runtimeTemplates,
  '/executions': routes.admin.executions,
  '/approvals': routes.admin.approvals,
  '/audit-logs': routes.admin.audit,
  '/usage': routes.admin.usage,
  '/quotas': routes.admin.quotas,
  '/settings': routes.admin.settings,
  '/secrets': routes.admin.secrets,
}
